# Generated by Django 3.0.8 on 2020-07-21 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cities_light', '0009_add_subregion'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystersUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_url', models.URLField(blank=True, max_length=255, verbose_name='Blog')),
                ('homepage_url', models.URLField(blank=True, max_length=255, verbose_name='Homepage')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='users/pictures/', verbose_name='Profile picture')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cities_light.Country', verbose_name='Country')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
