# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-07-22 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usersetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersetting',
            name='location_change',
            field=models.BooleanField(default=False, verbose_name='Get Notified on Change in Location for Meetups'),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='reminder',
            field=models.BooleanField(default=False, verbose_name="Get Reminders for rsvp'd Meetups"),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='time_change',
            field=models.BooleanField(default=False, verbose_name='Get Notified on Change in Timings for Meetups'),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='weekly_digest',
            field=models.BooleanField(default=True, verbose_name='Receive Weekly Digests from Communities'),
        ),
    ]
