# Generated by Django 3.0.8 on 2020-07-24 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Date created')),
                ('is_approved', models.BooleanField(default=True, verbose_name='Is approved')),
                ('body', models.TextField(verbose_name='Body')),
                ('object_id', models.PositiveIntegerField()),
            ],
        ),
    ]
