# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-04-04 08:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0013_auto_20200403_1757'),
        ('community', '0014_auto_20200324_1252'),
    ]

    operations = [
    ]
