# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-06-08 19:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0016_auto_20200606_0719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='location',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='cities_light.City', verbose_name='Location'),
        ),
    ]
