# Generated by Django 3.0.8 on 2020-07-21 18:28

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=150, verbose_name='Slug')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Date published')),
                ('date_modified', models.DateField(auto_now=True, verbose_name='Date last modified')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Content')),
                ('is_public', models.BooleanField(default=True, verbose_name='Is public')),
                ('is_monitored', models.BooleanField(default=False, verbose_name='Is monitored')),
            ],
            options={
                'verbose_name_plural': 'News',
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=150, verbose_name='Slug')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Date published')),
                ('date_modified', models.DateField(auto_now=True, verbose_name='Date last modified')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Content')),
                ('is_public', models.BooleanField(default=True, verbose_name='Is public')),
                ('is_monitored', models.BooleanField(default=False, verbose_name='Is monitored')),
            ],
        ),
        migrations.CreateModel(
            name='ResourceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
