from django.conf.urls import url

from .views import (CommunityLandingView, EditCommunityProfileView,
                    ViewCommunityProfileView, CommunityPageView,
                    AddCommunityPageView, EditCommunityPageView,
                    DeleteCommunityPageView, CommunityUsersView,
                    UserPermissionGroupsView, RequestCommunityView,
                    NewCommunityRequestsListView, ApproveRequestCommunityView,
                    RejectRequestCommunityView, ViewCommunityRequestView,
                    EditCommunityRequestView, AddCommunityView, CommunitySearch)


urlpatterns = [
    url(r'add_community/$', AddCommunityView.as_view(),
        name='add_community'),
    url(r'search/$', CommunitySearch.as_view(), name="search"),
    url(r'request_community/$', RequestCommunityView.as_view(),
        name='request_community'),
    url(r'community_requests', NewCommunityRequestsListView.as_view(),
        name='unapproved_community_requests'),
    url(r'^(?P<slug>[\w-]+)/edit_request/$', EditCommunityRequestView.as_view(),
        name='edit_community_request'),
    url(r'^(?P<slug>[\w-]+)/view_request/$', ViewCommunityRequestView.as_view(),
        name='view_community_request'),
    url(r'^(?P<slug>[\w-]+)/approve/$', ApproveRequestCommunityView.as_view(),
        name='approve_community_request'),
    url(r'(?P<slug>[\w-]+)/reject/$', RejectRequestCommunityView.as_view(),
        name='reject_community_request'),
    url(r'^(?P<slug>[\w-]+)/$', CommunityLandingView.as_view(),
        name='view_community_landing'),
    url(r'^(?P<slug>[\w-]+)/profile/$', ViewCommunityProfileView.as_view(),
        name='view_community_profile'),
    url(r'^(?P<slug>[\w-]+)/profile/edit/$',
        EditCommunityProfileView.as_view(), name='edit_community_profile'),
    url(r'^(?P<slug>[\w-]+)/p/add/$', AddCommunityPageView.as_view(),
        name="add_community_page"),
    url(r'^(?P<slug>[\w-]+)/p/(?P<page_slug>[\w-]+)/edit/$',
        EditCommunityPageView.as_view(), name="edit_community_page"),
    url(r'^(?P<slug>[\w-]+)/p/(?P<page_slug>[\w-]+)/delete/$',
        DeleteCommunityPageView.as_view(), name="delete_community_page"),
    url(r'^(?P<slug>[\w-]+)/p/(?P<page_slug>[\w-]+)/$',
        CommunityPageView.as_view(), name="view_community_page"),
    url(r'^(?P<slug>[\w-]+)/users/$', CommunityUsersView.as_view(),
        name="community_users"),
    url(r'^(?P<slug>[\w-]+)/user/(?P<username>[\w.@+-]+)/permissions/$',
        UserPermissionGroupsView.as_view(), name="user_permission_groups"),
]
