# Generated by Django 3.0.8 on 2020-07-21 18:28

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meetup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('date', models.DateField(verbose_name='Date')),
                ('end_date', models.DateField(null=True, verbose_name='End Date')),
                ('time', models.TimeField(blank=True, verbose_name='Time')),
                ('end_time', models.TimeField(null=True, verbose_name='End Time')),
                ('venue', models.CharField(blank=True, max_length=512, verbose_name='Venue')),
                ('description', models.TextField(verbose_name='Description')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last Update')),
                ('meetup_picture', models.ImageField(blank=True, null=True, upload_to='meetup/pictures/', verbose_name='Meetup picture')),
            ],
            options={
                'permissions': (('view_meetup_request', 'View Meetup Request'), ('approve_meetup_request', 'Approve Meetup Request'), ('reject_meetup_request', 'Reject Meetup Request'), ('add_meetups', 'Add Meetups'), ('delete_meetups', 'Delete Meetup'), ('change_meetups', 'Change Meetup'), ('add_meetup_rsvp', 'Add Meetup RSVP'), ('add_support_request', 'Add Support Request'), ('edit_support_request', 'Edit Support Request'), ('delete_support_request', 'Delete Support Request'), ('approve_support_request', 'Approve Support Request'), ('reject_support_request', 'Reject Support Request'), ('add_support_request_comment', 'Add Support Request Comment')),
            },
        ),
        migrations.CreateModel(
            name='RequestMeetup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('date', models.DateField(verbose_name='Date')),
                ('time', models.TimeField(blank=True, verbose_name='Time')),
                ('venue', models.CharField(blank=True, max_length=512, verbose_name='Venue')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Description')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Rsvp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coming', models.BooleanField(default=True)),
                ('plus_one', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SupportRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_approved', models.BooleanField(default=False)),
                ('meetup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetup.Meetup', verbose_name='Meetup')),
            ],
        ),
    ]
