# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-03-16 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='meetup_picture',
            field=models.ImageField(blank=True, null=True, upload_to='meetup/pictures/', verbose_name='Meetup picture'),
        ),
    ]
