# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-08 10:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetup',
            name='end_date',
        ),
    ]
