# Generated by Django 3.0.9 on 2020-08-04 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='is_virtual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meetup',
            name='meet_link',
            field=models.URLField(blank=True, null=True, verbose_name='Link for the Meeting'),
        ),
        migrations.AddField(
            model_name='requestmeetup',
            name='is_virtual',
            field=models.BooleanField(default=False),
        ),
    ]
