# Generated by Django 3.0.9 on 2020-08-05 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0005_meetup_start_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetup',
            name='start_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='link for the Host to start the Meeting'),
        ),
    ]
