# Generated by Django 3.0.9 on 2020-08-05 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0006_auto_20200805_0639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetup',
            name='start_url',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='link for the Host to start the Meeting'),
        ),
    ]
