# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-07-06 09:49
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0006_auto_20200620_2146'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetupImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='meetup/images', verbose_name='Meetup Image')),
            ],
        ),
        migrations.RemoveField(
            model_name='meetup',
            name='meetup_picture',
        ),
        migrations.AddField(
            model_name='meetup',
            name='resources',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Meetup Resources'),
        ),
        migrations.AddField(
            model_name='meetupimages',
            name='meetup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetup.Meetup', verbose_name='Meetup'),
        ),
    ]
