# Generated by Django 3.0.9 on 2020-08-05 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0007_auto_20200805_0641'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='meeting_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Meeting ID'),
        ),
    ]
