# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-07-06 11:24
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0007_auto_20200706_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetup',
            name='resources',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Meetup Resources'),
        ),
    ]
