# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-24 21:01
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_squashed_0003_auto_20160207_1550'),
        ('cities_light', '0006_compensate_for_0003_bytestring_bug'),
        ('meetup', '0012_auto_20160816_0752'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestMeetupLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name of the Meetup Location.(Naming convention for Systers meetup location is City+Systers.e.g.London Systers, Boston Systers.)')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='Slug of the Meetup Location')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Description of the Meetup Location')),
                ('email', models.EmailField(blank=True, max_length=255, verbose_name='Email of the Meetup Location if any.')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Is this Approved?')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approvedby', to='users.SystersUser', verbose_name='Approved By')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities_light.City', verbose_name='Location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='createdby', to='users.SystersUser', verbose_name='Requested By')),
            ],
        ),
        migrations.AlterField(
            model_name='meetup',
            name='venue',
            field=models.CharField(blank=True, max_length=512, verbose_name='Venue'),
        ),
        migrations.AlterField(
            model_name='meetuplocation',
            name='join_requests',
            field=models.ManyToManyField(blank=True, related_name='Join_Requests', to='users.SystersUser', verbose_name='Join Requests'),
        ),
    ]
