# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-09 17:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0013_auto_20180224_2101'),
        ('meetup', '0013_auto_20180115_1044'),
    ]

    operations = [
    ]
