# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-24 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0014_auto_20180126_0505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetuplocation',
            name='join_requests',
            field=models.ManyToManyField(blank=True, related_name='Join_Requests', to='users.SystersUser', verbose_name='Join Requests'),
        ),
    ]
