# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-06 10:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0015_auto_20180309_1734'),
        ('meetup', '0014_auto_20180301_0948'),
    ]

    operations = [
    ]
