# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-09 16:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0015_auto_20180224_2133'),
        ('meetup', '0013_auto_20180224_2101'),
    ]

    operations = [
    ]
