# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-28 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0017_auto_20180506_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='end_date',
            field=models.DateField(null=True, verbose_name='End Date'),
        ),
    ]
