# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-31 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0018_meetup_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetup',
            name='description',
            field=models.CharField(max_length=1000, verbose_name='Description'),
        ),
    ]
