# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-31 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0020_auto_20180731_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetup',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='meetup',
            name='venue',
            field=models.CharField(blank=True, max_length=512, verbose_name='Venue'),
        ),
    ]
